### ISSUE TITLE
Falha na execução dos testes da aplicação recém criada

### ISSUE THREAD

**Issue by jeanclaybr** [tst-labs/react-starter#20]
Passos para reprodução do erro:

Executar: `npx create-react-app my-react-app --template @tst-labs/react-starter`
Depois, dentro do diretório da aplicação: `CI=true yarn test`

A mensagem de erro é:

```
yarn run v1.22.4                                                                                                                                                               
$ react-scripts test                                                                                                                                                           
FAIL src/app/app.test.js
  ● Test suite failed to run

    Cannot find module '@testing-library/jest-dom/extend-expect' from 'src/setupTests.js'

      3 | // expect(element).toHaveTextContent(/react/i)
      4 | // learn more: https://github.com/testing-library/jest-dom
    > 5 | import '@testing-library/jest-dom/extend-expect';
        | ^
      6 |

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/setupTests.js:5:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.756 s
Ran all test suites.
error Command failed with exit code 1.                                                                                                                                         
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Versão do yarn: v1.22.4
Versão do nodejs: 16.14.2

**Comment by adriano-lemos-dev** [comment]
Aparentemente, a nova versão do CRA não está usando os valores na chave `dependencies` do arquivo `template.json` na hora de juntar com as dependências da template padrão. Assim, o `package.json` gerado não contem dependências vitais para a execução do projeto gerado.

Será necessário uma atualização do projeto e novos testes locais.
